### ISSUE TITLE
what about binary files?

### ISSUE THREAD

**Issue by mspanish** [Conduitry/do-not-zip#3]
Hey what if my file is already a Buffer? I am trying to save Adobe Swatch Exchange files, and they are already converted to buffers for the browser. I guess PNG files would apply here too.

thanks again for the nice lean script :)

**Comment by Conduitry** [comment]
I've update the readme to make stuff a bit clearer. Each file can be specified as a string, or as anything that can be ~~iterated over and returns byte integers~~ indexed and give you integers - which includes regular arrays of bytes, but also includes Blobs and Buffers too.

**Comment by mspanish** [comment]
I'm trying using to the following code, first is a fn that returns the data with a blob in it

`return {path: 'swatch.ase', data:b}`

Then I try creating a zip file to download

`const blob = doNotZip.toBlob(data);`

The initial "b"  is definitely a correctly formed blob of a swatch, which I can save as a binary file using console.save, and I've tested that it's a working .ase Illustrator swatch file.  Yet whether I use toBlob or toArray - I get the same error in Chrome:

`index.es.js:12 Uncaught TypeError: bytes is not iterable
    at crc32 (index.es.js:12)
    at toArray (index.es.js:35)
    at toBlob (index.es.js:42)
    at PalettesExport.exportFiles (PalettesExport.html:394)
    at HTMLButtonElement.click_handler_1 (PalettesExport.html:15)`

**Comment by mspanish** [comment]
Data is definitely an array of values, in this case I have only 1 file but it's in an array before being passed to the fn.

**Comment by mspanish** [comment]
Same thing whether I pass an ArrayBuffer or a Blob, I get the bytes is not iterable error.

**Comment by Conduitry** [comment]
Ah! Apparently I was wrong about `Blob`s. Those can't be indexed to retrieve their bytes - there's not even a synchronous way to extract the bytes from a `Blob`. I'll have to dig around to see what's going to be possible (I'd like to keep a synchronous API if at all possible), but if you can pass an actual array of byte values, that should work. I'll update the readme in the meantime.

**Comment by mspanish** [comment]
Hmm - I'm starting out with just JSON, which contains the value of colors to be passed to an Adobe Swatch Exchange file.  This file than parses that and throws me back the ArrayBuffer. If you see anything I can do here to make an array of byte values, I'd be happy to try it out!

```
import { ByteBuffer } from './byte-buffer.js';
import { constants } from './constants.js';

let encode = (data) => {

  let colors = data.colors;
  let numberOfSwatches = data.colors.length;
  let ase = new ByteBuffer();

  ase.writeString(constants.FILE_SIGNATURE);
	//ase.writeUTF8String(constants.FILE_SIGNATURE);
	ase.writeInt(constants.FORMAT_VERSION);
	ase.writeInt(numberOfSwatches); // number of blocks

  for (var i = 0; i < numberOfSwatches; i++) {

    var color = colors[i],
        swatch = new ByteBuffer(),
        j=null;

    // block type
    // (0xc001 ⇒ Group start, 0xc002 ⇒ Group end, 0x0001 ⇒ Color entry)
    ase.writeShort(constants.COLOR_START);

    // Group/Color name
    // 0-terminated string of length (uint16) double-byte characters
    swatch.writeShort(color.name.length + 1);
    for(j=0; j < color.name.length; j++) {
      swatch.writeShort(color.name.charCodeAt(j));
    }
    swatch.writeShort(0); // terminate with 0

    // color model - 4*char (CMYK, RGB, LAB or Gray)
    var model = color.model.length == 4 ? color.model : color.model + " ";
    swatch.writeUTF8String(model);

    // color values
    // CMYK ⇒ 4*float32 / RGB & LAB ⇒ 3*float32 / Gray ⇒ 1*float32
    for(j=0; j < constants.COLOR_SIZES[color.model.toUpperCase()]; j++) {
      swatch.writeFloat(color.color[j]);
    }

    // color type - 1*int16 (0 ⇒ Global, 1 ⇒ Spot, 2 ⇒ Normal)
    swatch.writeShort(constants.WRITE_COLOR_TYPES[color.type]);

    // block length - 1*int32
		ase.writeInt(swatch.offset);

    // add to ase buffer
    swatch.flip();
		ase.append(swatch);
	}

  ase.flip();
	return ase.toBuffer();

	}

export { encode };
```

**Comment by mspanish** [comment]
The bytebuffer library file I'm importing into Svelte is here: [bytebuffer](https://github.com/dcodeIO/bytebuffer.js/blob/master/dist/bytebuffer.js)

**Comment by mspanish** [comment]
[This](https://github.com/yellcorp/es6lib-abstream) looks interesting - Synchronous stream-like interfaces for reading and writing byte sequences, integers and floats to and from ArrayBuffers and TypedArrays.

**Comment by Conduitry** [comment]
If you have an `ArrayBuffer`, you should be able to convert it to a byte array with `new Uint8Array(arrayBuffer)` and pass that as the file data to this library.

**Comment by mspanish** [comment]
Works perfectly thank you!!
